services:
  - type: web
    name: diabetes-prediction-app
    env: python
    buildCommand: |
      # Install Python dependencies first
      pip install -r requirements.txt
      # Build frontend
      cd frontend
      echo "=== BUILD DIAGNOSTICS ==="
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      echo "Current directory: $(pwd)"
      echo "Contents of current directory:"
      ls -la
      echo "=== INSTALLING DEPENDENCIES ==="
      npm install
      echo "=== BUILDING FRONTEND ==="
      npm run build
      echo "=== BUILD COMPLETE ==="
      echo "Contents after build:"
      ls -la
      if [ -d "build" ]; then
        echo "Build directory exists:"
        ls -la build/
        echo "Copying build to root directory..."
        cp -r build ../frontend-build
      else
        echo "ERROR: Build directory not found!"
        echo "This is likely the cause of the frontend not loading."
      fi
      cd ..
      echo "=== ROOT DIRECTORY CONTENTS ==="
      ls -la
      if [ -d "frontend-build" ]; then
        echo "Frontend build successfully copied to root:"
        ls -la frontend-build/
      fi
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15
      - key: NODE_VERSION
        value: 18.17.0